"""initial schema

Revision ID: 3179cf93a5f4
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3179cf93a5f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'cancelled')", name='ck_experiment_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('taxa',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('scientific_name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('experiment_protocols',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('seed_count_per_dish', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('seed_count_per_dish IS NULL OR seed_count_per_dish > 0', name='ck_protocol_seed_count'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    op.create_table('import_jobs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_timepoints',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('day_after_sowing', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('day_after_sowing >= 0', name='ck_timepoint_day'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'day_after_sowing', name='uq_timepoint_day')
    )
    with op.batch_alter_table('measurement_timepoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_timepoints_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('seed_lots',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('taxon_id', sa.String(length=36), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name='ck_seed_lot_quantity'),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('seed_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seed_lots_taxon_id'), ['taxon_id'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('experiment_materials',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('seed_lot_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seed_lot_id'], ['seed_lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'seed_lot_id', name='uq_material_experiment_lot')
    )
    with op.batch_alter_table('experiment_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_materials_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_materials_seed_lot_id'), ['seed_lot_id'], unique=False)

    op.create_table('germination_dishes',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('seed_count', sa.Integer(), nullable=False),
    sa.Column('sown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('seed_count > 0', name='ck_dish_seed_count'),
    sa.ForeignKeyConstraint(['material_id'], ['experiment_materials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'label', name='uq_dish_label')
    )
    with op.batch_alter_table('germination_dishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_germination_dishes_material_id'), ['material_id'], unique=False)

    op.create_table('germination_observations',
    sa.Column('dish_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_germinated_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('new_germinated_count >= 0', name='ck_observation_count'),
    sa.ForeignKeyConstraint(['dish_id'], ['germination_dishes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'observed_at', name='uq_observation_time')
    )
    with op.batch_alter_table('germination_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_germination_observations_dish_id'), ['dish_id'], unique=False)

    op.create_table('seedling_samples',
    sa.Column('dish_id', sa.String(length=36), nullable=False),
    sa.Column('sample_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sample_number > 0', name='ck_sample_number'),
    sa.ForeignKeyConstraint(['dish_id'], ['germination_dishes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'sample_number', name='uq_sample_number')
    )
    with op.batch_alter_table('seedling_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seedling_samples_dish_id'), ['dish_id'], unique=False)

    op.create_table('seedling_measurements',
    sa.Column('sample_id', sa.String(length=36), nullable=False),
    sa.Column('timepoint_id', sa.String(length=36), nullable=False),
    sa.Column('root_length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shoot_length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('root_length_mm IS NULL OR root_length_mm >= 0', name='ck_root_length'),
    sa.CheckConstraint('shoot_length_mm IS NULL OR shoot_length_mm >= 0', name='ck_shoot_length'),
    sa.ForeignKeyConstraint(['sample_id'], ['seedling_samples.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timepoint_id'], ['measurement_timepoints.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'timepoint_id', name='uq_sample_timepoint')
    )
    with op.batch_alter_table('seedling_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seedling_measurements_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seedling_measurements_timepoint_id'), ['timepoint_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seedling_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seedling_measurements_timepoint_id'))
        batch_op.drop_index(batch_op.f('ix_seedling_measurements_sample_id'))

    op.drop_table('seedling_measurements')
    with op.batch_alter_table('seedling_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seedling_samples_dish_id'))

    op.drop_table('seedling_samples')
    with op.batch_alter_table('germination_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_germination_observations_dish_id'))

    op.drop_table('germination_observations')
    with op.batch_alter_table('germination_dishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_germination_dishes_material_id'))

    op.drop_table('germination_dishes')
    with op.batch_alter_table('experiment_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_materials_seed_lot_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_materials_experiment_id'))

    op.drop_table('experiment_materials')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('seed_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seed_lots_taxon_id'))

    op.drop_table('seed_lots')
    with op.batch_alter_table('measurement_timepoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_timepoints_experiment_id'))

    op.drop_table('measurement_timepoints')
    op.drop_table('import_jobs')
    op.drop_table('experiment_protocols')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('taxa')
    op.drop_table('experiments')
    # ### end Alembic commands ###
